version: '3'
services:
  database:
    container_name: postgres_container
    image: "postgres" 
    env_file:
      - database.env 
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
        - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  redis:
    container_name: redis_container
    image: redis:latest
    command: redis-server --requirepass CGqbab5CQyDKpyAa
    ports:
        - "6379:6379"    
volumes:
    postgres: