"""Created model

Revision ID: 56ba824b4124
Revises: 
Create Date: 2021-11-07 17:08:00.997205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ba824b4124'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remove_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill',
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remove_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_exp',
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remove_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('begin_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remove_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('second_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('position', sa.String(length=32), nullable=False),
    sa.Column('recruit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('skill_point', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_email'), 'person', ['email'], unique=True)
    op.create_index(op.f('ix_person_phone_number'), 'person', ['phone_number'], unique=True)
    op.create_table('person_skills',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'skill_id')
    )
    op.create_table('test',
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remove_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('questions', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_creator_id'), 'test', ['creator_id'], unique=False)
    op.create_index(op.f('ix_test_skill_id'), 'test', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_skill_id'), table_name='test')
    op.drop_index(op.f('ix_test_creator_id'), table_name='test')
    op.drop_table('test')
    op.drop_table('person_skills')
    op.drop_index(op.f('ix_person_phone_number'), table_name='person')
    op.drop_index(op.f('ix_person_email'), table_name='person')
    op.drop_table('person')
    op.drop_table('work_exp')
    op.drop_table('skill')
    op.drop_table('role')
    # ### end Alembic commands ###
